name: Unit tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        ports: [ '5432:5432' ]
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          POSTGRES_PASSWORD: 12345
    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.6
      - name: Run the default task
        env:
          DB_HOST: localhost
          DB_USERNAME: postgres
          PGPASSWORD: 12345
          RAILS_ENV: test
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler -v 2.5.23
          mv .env.test .env
          bundle install
          bundle exec rails db:create
          bundle exec rails db:migrate
          bundle exec rails db:seed
          bundle exec rspec
